twig:
    default_path: '%kernel.project_dir%/templates'

    # activation du thème BootStrap 5 pour les formulaires du site
    form_themes: ['bootstrap_5_layout.html.twig']

    globals:

        # Récupération de la clé Recaptcha depuis le fichier services.yaml
        google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'

when@test:
    twig:
        strict_variables: true
